apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-extensions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


